apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
            items:
              - key: KUBECONFIG
                path: /kubeconfig
      containers:
        - name: wisecow
          image: rishabsingh12/wisecow-app:latest
          ports:
            - containerPort: 4499
          env:
            - name: KUBECONFIG
              value: /kubeconfig
