name: Deploy to EKS

on:
  push:
    branches:
      - main  # Adjust this if you want to trigger on a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Check if EKS cluster exists
      run: aws eks describe-cluster --name mycluster --region us-east-1

    - name: Configure kubectl
      run: aws eks update-kubeconfig --name mycluster --region us-east-1

    - name: Apply Cluster Role and Role Binding
      run: |
        kubectl apply -f clusterrole.yaml
        kubectl apply -f clusterrolebinding.yaml

    - name: Apply Deployment and Service
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify Deployment
      run: kubectl rollout status deployment/wisecow-deployment
