name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wisecow-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
          KUBECONFIG_PATH: apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
            items:
              - key: KUBECONFIG
                path: /kubeconfig
      containers:
        - name: wisecow
          image: rishabsingh12/wisecow-app:latest
          ports:
            - containerPort: 4499
          env:
            - name: KUBECONFIG
              value: /home/ubuntu/.kube/config
          volumeMounts:
            - name: kubeconfig
              mountPath: /home/ubuntu/.kube/config

        run: |
          echo "$KUBECONFIG" > "$KUBECONFIG_PATH"
          chmod 600 "$KUBECONFIG_PATH"
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
      - name: Save kubeconfig
        run: |
          echo "$KUBECONFIG" > "$KUBECONFIG_PATH"
          chmod 600 "$KUBECONFIG_PATH"
