name: CI/CD Pipeline

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create kubeconfig
        run: |
          mkdir -p ${HOME}/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config

      - name: Deploy to EKS
        run: kubectl run nginx --image=nginx
